import { LineEdit, VerticalBox, ComboBox } from "std-widgets.slint";
import { Category } from "../View_Expenses/items.slint";

/*
    So this module contains code for Home Page that involves marking expenses made so far.
    This module contains components for Entering Name and Cost of Item
*/

export component Amt inherits VerticalLayout{
    
    // property is attached or made the alias of a child element's property
    // any change in value of amt's text will change the value of property 'amount'
    in-out property <string> amount <=> amt.text;
    Text{
        text: "Cost";
        font-size: 18px;
        color: #436b41;
        horizontal-alignment: center;
        font-family: "Century";
    }
    amt:= LineEdit {
        placeholder-text: "Enter cost";
        width: 101px;
        horizontal-alignment: center;
        input-type: number;
    }
}

export component Name inherits VerticalLayout {
    // The i_name property is attached to the child element (name)'s 'text' property.
    // Any change to the child's text property will be seen in the parent's i_name property!
    in-out property <string> i_name <=> name.text;
    Text{
        text: "Name";
        font-size: 18px;
        color: #436b41;
        horizontal-alignment: center;
        font-family: "Century";
    }
    name:= LineEdit {
        placeholder-text: "Enter name";
        width: 101px;
        horizontal-alignment: center;
    }
}


export component Category inherits VerticalLayout {
    // The i_category property is attached to the child element (category)'s 'text' property.
    // Any change to the child's text property will be seen in the parent's i_name property!
    in-out property <string> i_category <=> category.current-value;
    Text{
        text: "Category";
        font-size: 18px;
        color: #436b41;
        horizontal-alignment: center;
        font-family: "Century";
    }

    category:= ComboBox {
        x: 190px;
        current-value: "Work";
        model: ["Work", "Utility", "Entertainment", "Travel", "Food", "Subscriptions"];
        width: 120px;
    }
}