import { LineEdit } from "std-widgets.slint";
import { ItemInfo } from "item_info.slint";


export enum Category { Work, Utility, Entertainment, Travel, Food, Subscriptions }
export component ItemContainer inherits Rectangle {

    // Size of scroll view container.
    width: 410px;

    in-out property <string> item_name 
    <=> iname.text;
    in-out property <string> item_cost
    <=> icost.text;
    in-out property <Category> item_category;



    // Main Rectangle
    Rectangle {
        height: 65px;

        // Category Rectangle
        Rectangle {
            x: 0;
            height: 50px;
            width: 410px;
            in-out property <Category> icategory;
            background: {
                if (icategory == Category.Food) {
                    green;
                }
                if(icategory == Category.Entertainment) {
                    yellow;
                }
                blue;
            }


            iname := ItemInfo {
                height: parent.height;
                info_x: 0px;
            }
           
            icost := ItemInfo{
                height: parent.height;
                info_x: 200px;
            }

            
        }

    }
}
