export component ItemInfo inherits Rectangle {

    in-out property <length> info_x: 25px;
    in-out property <bool> read-only <=> text_input.read-only;
    in-out property <string> text <=> text_input.text;

    in-out property <bool> beingEdited;

    Rectangle {
        background: white;
        x: info_x + 20 * 1px;
        width: 180px;
        height: 30px;

        border-radius: 10px;
        border-color: black;
        border-width: 1px;

        opacity: {
            beingEdited ?
            0.9 :
            0.5
        };

        text_input := TextInput {
            // x: info_x + 10 * 1px;
            width: 190px;
            horizontal-alignment: center;
            vertical-alignment: center;
            read-only: true;
        }
    }
}