
export component TopCredits inherits Rectangle{
    Rectangle {
        x: parent.x;
        y: parent.y;
        width: 100px;
        height: 50px;
        background: #065F18;
        Text {
            horizontal-alignment: center;
            color: white;
            font-size: 11px;
            text: "Expense Tracker\nv1.0";
        }
    }
}


export component BottomCredits inherits Rectangle{
    Rectangle {
        x: parent.x;
        y: 350px;
        width: 100px;
        height: 50px;
        background: #065F18;
        Text {
            horizontal-alignment: center;
            color: white;
            font-size: 11px;
            text: "@isuboi";
        }
    }
}

